In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## Import data (bp_electricity_generation_TWh_from_1965) and clean data

In [2]:
bp_electricity_generation = pd.read_csv('../data/Source of Data - BP/bp_electricity_generation_TWh_from_1965.csv',skiprows=2)

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
bp_electricity_generation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 42 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Terawatt-hours  109 non-null    object
 1   1985            99 non-null     float64
 2   1986            99 non-null     float64
 3   1987            99 non-null     float64
 4   1988            99 non-null     float64
 5   1989            99 non-null     float64
 6   1990            102 non-null    float64
 7   1991            102 non-null    float64
 8   1992            102 non-null    float64
 9   1993            102 non-null    float64
 10  1994            102 non-null    float64
 11  1995            102 non-null    float64
 12  1996            102 non-null    float64
 13  1997            102 non-null    float64
 14  1998            102 non-null    float64
 15  1999            102 non-null    float64
 16  2000            102 non-null    float64
 17  2001            102 non-null    float64
 18  2002            102 non-null    float64
 19  2003            102 non-null    float64
 20  2004            102 non-null    float64
 21  2005            102 non-null    float64
 22  2006            102 non-null    float64
 23  2007            102 non-null    float64
 24  2008            102 non-null    float64
 25  2009            102 non-null    float64
 26  2010            102 non-null    float64
 27  2011            102 non-null    float64
 28  2012            102 non-null    float64
 29  2013            102 non-null    float64
 30  2014            102 non-null    float64
 31  2015            102 non-null    float64
 32  2016            102 non-null    float64
 33  2017            102 non-null    float64
 34  2018            102 non-null    float64
 35  2019            102 non-null    float64
 36  2020            102 non-null    float64
 37  2020.1          102 non-null    object
 38  2009-19         102 non-null    object
 39  2020.2          102 non-null    object
 40  Unnamed: 40     0 non-null      float64
 41  Unnamed: 41     0 non-null      float64
dtypes: float64(38), object(4)
memory usage: 38.8+ KB

In [5]:
bp_electricity_generation.head(2)

,Terawatt-hours,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2020.1,2009-19,2020.2,Unnamed: 40,Unnamed: 41
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Canada,459.0,468.6,496.4,506.0,498.1,480.6,507.0,518.6,530.2,553.1,557.9,571.6,572.3,562.0,577.8,603.8,587.8,599.8,588.3,598.5,624.2,612.0,637.1,635.1,613.9,607.0,638.3,636.5,655.7,647.6,659.3,663.7,660.1,655.8,648.7,643.9,-1.0%,0.6%,2.4%,NaN,NaN

In [6]:
bp_electricity_generation.drop(bp_electricity_generation.columns[[40,41]], axis=1, inplace=True)

In [7]:
bp_electricity_generation.head(2)

,Terawatt-hours,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2020.1,2009-19,2020.2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Canada,459.0,468.6,496.4,506.0,498.1,480.6,507.0,518.6,530.2,553.1,557.9,571.6,572.3,562.0,577.8,603.8,587.8,599.8,588.3,598.5,624.2,612.0,637.1,635.1,613.9,607.0,638.3,636.5,655.7,647.6,659.3,663.7,660.1,655.8,648.7,643.9,-1.0%,0.6%,2.4%

In [8]:
bp_electricity_generation.rename(columns = {'2020.1':'growth_rate 2020', '2009-19': 'growth_rate 2009-19', '2020.2': 'share 2020'}, inplace = True)

In [9]:
bp_electricity_generation.head(2)

,Terawatt-hours,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,growth_rate 2020,growth_rate 2009-19,share 2020
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Canada,459.0,468.6,496.4,506.0,498.1,480.6,507.0,518.6,530.2,553.1,557.9,571.6,572.3,562.0,577.8,603.8,587.8,599.8,588.3,598.5,624.2,612.0,637.1,635.1,613.9,607.0,638.3,636.5,655.7,647.6,659.3,663.7,660.1,655.8,648.7,643.9,-1.0%,0.6%,2.4%

In [10]:
bp_electricity_generation.drop([0], axis=0, inplace = True)

In [11]:
bp_electricity_generation.head(2)

,Terawatt-hours,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,growth_rate 2020,growth_rate 2009-19,share 2020
1,Canada,459.0,468.6,496.4,506.0,498.1,480.6,507.0,518.6,530.2,553.1,557.9,571.6,572.3,562.0,577.8,603.8,587.8,599.8,588.3,598.5,624.2,612.0,637.1,635.1,613.9,607.0,638.3,636.5,655.7,647.6,659.3,663.7,660.1,655.8,648.7,643.9,-1.0%,0.6%,2.4%
2,Mexico,96.2,99.6,106.2,112.2,120.0,117.6,128.6,132.3,134.6,146.1,150.4,156.6,166.7,181.1,190.0,203.6,210.2,215.7,224.9,235.4,248.0,256.2,263.2,269.3,267.8,275.6,292.1,296.4,297.1,303.3,310.3,319.4,325.1,335.1,322.6,313.2,-3.2%,1.9%,1.2%

In [12]:
bp_electricity_generation.tail(15)

,Terawatt-hours,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,growth_rate 2020,growth_rate 2009-19,share 2020
103,Other Asia Pacific,37.3,38.7,40.8,43.3,45.3,45.1,44.1,42.9,41.3,43.4,44.3,43.7,42.3,41.5,44.5,47.6,49.3,49.6,52.2,54.3,56.7,59.9,63.6,66.6,65.3,72.5,76.8,78.2,84.5,88.6,91.4,109.3,119.7,116.0,127.5,131.8,3.1%,6.9%,0.5%
104,Total Asia Pacific,1723.9,1815.7,1971.4,2123.8,2287.7,2468.9,2635.5,2779.9,2918.3,3175.7,3395.3,3571.4,3742.4,3849.1,4039.0,4285.7,4478.0,4762.2,5098.7,5567.6,5971.3,6456.8,7014.7,7302.2,7537.5,8257.7,8875.1,9278.1,9812.3,10333.7,10433.9,10947.6,11569.8,12339.3,12741.6,12919.3,1.1%,5.4%,48.2%
105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,Total World,9880.0,10174.8,10665.1,11134.9,11654.0,11957.3,12218.4,12329.8,12591.7,12916.6,13375.2,13789.2,14120.5,14502.9,14917.8,15555.5,15788.9,16345.5,16924.0,17726.7,18454.1,19155.3,20046.0,20421.6,20264.9,21570.7,22257.0,22806.3,23435.2,24031.7,24270.5,24915.2,25623.9,26659.1,27001.0,26823.2,-0.9%,2.9%,100.0%
107,of which: OECD,6561.1,6667.7,6949.6,7233.0,7606.3,7812.9,7986.5,8047.4,8229.1,8451.4,8717.0,8960.6,9128.4,9367.8,9578.7,9908.0,9903.7,10129.9,10249.7,10501.2,10740.7,10827.9,11066.5,11071.1,10640.3,11062.8,11014.3,11023.7,11015.6,10956.6,11005.0,11082.8,11119.5,11312.8,11168.4,10880.8,-2.8%,0.5%,40.6%
108,Non-OECD,3318.8,3507.1,3715.6,3902.0,4047.7,4144.4,4232.0,4282.4,4362.6,4465.2,4658.2,4828.7,4992.1,5135.1,5339.1,5647.5,5885.1,6215.6,6674.4,7225.6,7713.4,8327.4,8979.5,9350.5,9624.6,10507.9,11242.7,11782.6,12419.7,13075.2,13265.5,13832.4,14504.4,15346.4,15832.5,15942.4,0.4%,5.1%,59.4%
109,European Union #,2022.9,2076.0,2148.3,2198.4,2249.4,2275.2,2317.9,2303.6,2304.1,2339.2,2409.6,2491.5,2507.6,2562.4,2587.3,2660.6,2734.9,2755.6,2839.0,2911.7,2928.9,2973.9,2987.5,2999.7,2847.6,2982.6,2931.3,2932.3,2912.9,2851.1,2899.1,2920.1,2952.4,2937.5,2892.5,2770.6,-4.5%,0.2%,10.3%
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,Source: statistics are taken from national sta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,* Based on gross output.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,♦ Less than 0.05%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,"USSR includes CIS, Georgia, Ukraine and the Ba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,# Excludes Croatia and Slovenia prior to 1990.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,Notes: Annual changes and share of total are c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Growth rates are adjusted for leap years.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
bp_electricity_generation = bp_electricity_generation.drop(index=[104,110,111,112,113,114,115,116,117])
bp_electricity_generation.tail(8)

,Terawatt-hours,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,growth_rate 2020,growth_rate 2009-19,share 2020
101,Thailand,23.0,24.7,28.6,32.4,37.4,44.1,50.1,57.0,63.3,71.1,79.7,87.0,92.7,89.5,90.2,95.5,101.0,108.4,115.9,124.1,130.4,136.8,142.5,145.4,145.9,157.6,153.3,169.0,168.6,173.8,177.8,179.8,176.7,177.6,186.5,176.4,-5.7%,2.5%,0.7%
102,Vietnam,5.1,5.5,6.1,6.8,7.8,8.7,9.2,9.7,10.7,12.3,14.6,16.9,19.1,21.7,23.6,26.6,30.6,35.8,40.9,46.2,52.1,57.9,64.1,71.0,80.6,91.7,101.5,115.1,124.5,141.3,157.9,175.7,191.6,209.2,227.5,234.5,2.8%,10.9%,0.9%
103,Other Asia Pacific,37.3,38.7,40.8,43.3,45.3,45.1,44.1,42.9,41.3,43.4,44.3,43.7,42.3,41.5,44.5,47.6,49.3,49.6,52.2,54.3,56.7,59.9,63.6,66.6,65.3,72.5,76.8,78.2,84.5,88.6,91.4,109.3,119.7,116.0,127.5,131.8,3.1%,6.9%,0.5%
105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,Total World,9880.0,10174.8,10665.1,11134.9,11654.0,11957.3,12218.4,12329.8,12591.7,12916.6,13375.2,13789.2,14120.5,14502.9,14917.8,15555.5,15788.9,16345.5,16924.0,17726.7,18454.1,19155.3,20046.0,20421.6,20264.9,21570.7,22257.0,22806.3,23435.2,24031.7,24270.5,24915.2,25623.9,26659.1,27001.0,26823.2,-0.9%,2.9%,100.0%
107,of which: OECD,6561.1,6667.7,6949.6,7233.0,7606.3,7812.9,7986.5,8047.4,8229.1,8451.4,8717.0,8960.6,9128.4,9367.8,9578.7,9908.0,9903.7,10129.9,10249.7,10501.2,10740.7,10827.9,11066.5,11071.1,10640.3,11062.8,11014.3,11023.7,11015.6,10956.6,11005.0,11082.8,11119.5,11312.8,11168.4,10880.8,-2.8%,0.5%,40.6%
108,Non-OECD,3318.8,3507.1,3715.6,3902.0,4047.7,4144.4,4232.0,4282.4,4362.6,4465.2,4658.2,4828.7,4992.1,5135.1,5339.1,5647.5,5885.1,6215.6,6674.4,7225.6,7713.4,8327.4,8979.5,9350.5,9624.6,10507.9,11242.7,11782.6,12419.7,13075.2,13265.5,13832.4,14504.4,15346.4,15832.5,15942.4,0.4%,5.1%,59.4%
109,European Union #,2022.9,2076.0,2148.3,2198.4,2249.4,2275.2,2317.9,2303.6,2304.1,2339.2,2409.6,2491.5,2507.6,2562.4,2587.3,2660.6,2734.9,2755.6,2839.0,2911.7,2928.9,2973.9,2987.5,2999.7,2847.6,2982.6,2931.3,2932.3,2912.9,2851.1,2899.1,2920.1,2952.4,2937.5,2892.5,2770.6,-4.5%,0.2%,10.3%