In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
renew_gen_by_source = pd.read_csv('../data/Source of Data - BP/bp_renewables_generation_by_source.csv',skiprows=2)

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
renew_gen_by_source.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Terawatt-hours       90 non-null     object
 1   Wind                 83 non-null     object
 2   Solar                83 non-null     object
 3   Other renewables*    83 non-null     object
 4   Total                83 non-null     object
 5   Wind.1               83 non-null     object
 6   Solar.1              83 non-null     object
 7   Other renewables*.1  83 non-null     object
 8   Total.1              83 non-null     object
 9   Wind.2               83 non-null     object
 10  Solar.2              83 non-null     object
 11  Other renewables*.2  83 non-null     object
 12  Total.2              83 non-null     object
 13  Unnamed: 13          0 non-null      float64
 14  Unnamed: 14          0 non-null      float64
dtypes: float64(2), object(13)
memory usage: 11.7+ KB

In [5]:
renew_gen_by_source.head(2)

,Terawatt-hours,Wind,Solar,Other renewables*,Total,Wind.1,Solar.1,Other renewables*.1,Total.1,Wind.2,Solar.2,Other renewables*.2,Total.2,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Canada,32.7,4.2,10.3,47.1,36.1,4.4,10.7,51.2,10.24%,4.63%,3.93%,8.36%,NaN,NaN

In [6]:
renew_gen_by_source.drop([0], axis=0, inplace = True) 
renew_gen_by_source.head(2)

,Terawatt-hours,Wind,Solar,Other renewables*,Total,Wind.1,Solar.1,Other renewables*.1,Total.1,Wind.2,Solar.2,Other renewables*.2,Total.2,Unnamed: 13,Unnamed: 14
1,Canada,32.7,4.2,10.3,47.1,36.1,4.4,10.7,51.2,10.24%,4.63%,3.93%,8.36%,NaN,NaN
2,Mexico,16.7,7.4,8.2,32.3,19.7,11.9,7.6,39.2,17.49%,60.74%,-7.91%,20.89%,NaN,NaN

In [7]:
renew_gen_by_source.columns

Index(['Terawatt-hours', 'Wind', 'Solar', 'Other renewables*', 'Total',
       'Wind.1', 'Solar.1', 'Other renewables*.1', 'Total.1', 'Wind.2',
       'Solar.2', 'Other renewables*.2', 'Total.2', 'Unnamed: 13',
       'Unnamed: 14'],
      dtype='object')

In [8]:
renew_gen_by_source.rename(columns = {'Wind':'2019 Wind','Solar':'2019 Solar','Other renewables':'2019 Other Renewables',
                                      'Total':'2019 Total','Wind.1':'2020 Wind','Solar.1':'2020 Solar','Other renewables#.1':'2020 Other Renewables',
                                     'Total.1':'2020 Total','Wind.2':'2020 Growth Rate Wind','Solar.2':'2020 Growth Rate Solar',
                                      'Other renewables#.2':'2020 Growth Rate Other renewables','Total.2':'2020 Growth Rate Total'}, inplace = True)
renew_gen_by_source.head(2)

,Terawatt-hours,2019 Wind,2019 Solar,Other renewables*,2019 Total,2020 Wind,2020 Solar,Other renewables*.1,2020 Total,2020 Growth Rate Wind,2020 Growth Rate Solar,Other renewables*.2,2020 Growth Rate Total,Unnamed: 13,Unnamed: 14
1,Canada,32.7,4.2,10.3,47.1,36.1,4.4,10.7,51.2,10.24%,4.63%,3.93%,8.36%,NaN,NaN
2,Mexico,16.7,7.4,8.2,32.3,19.7,11.9,7.6,39.2,17.49%,60.74%,-7.91%,20.89%,NaN,NaN

In [9]:
cols = [13,14]
renew_gen_by_source.drop(renew_gen_by_source.columns[cols], axis=1, inplace=True)

In [10]:
renew_gen_by_source.head(2)

,Terawatt-hours,2019 Wind,2019 Solar,Other renewables*,2019 Total,2020 Wind,2020 Solar,Other renewables*.1,2020 Total,2020 Growth Rate Wind,2020 Growth Rate Solar,Other renewables*.2,2020 Growth Rate Total
1,Canada,32.7,4.2,10.3,47.1,36.1,4.4,10.7,51.2,10.24%,4.63%,3.93%,8.36%
2,Mexico,16.7,7.4,8.2,32.3,19.7,11.9,7.6,39.2,17.49%,60.74%,-7.91%,20.89%

In [11]:
renew_gen_by_source.tail(15)

,Terawatt-hours,2019 Wind,2019 Solar,Other renewables*,2019 Total,2020 Wind,2020 Solar,Other renewables*.1,2020 Total,2020 Growth Rate Wind,2020 Growth Rate Solar,Other renewables*.2,2020 Growth Rate Total
84,Other Asia Pacific,0.5,0.8,0.3,1.5,0.5,1.1,0.2,1.7,-0.28%,27.37%,-10.88%,12.84%
85,Total Asia Pacific,509.4,392.0,247.8,1149.2,572.6,470.3,279.1,1322.0,12.11%,19.63%,12.31%,14.72%
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Total World,1418.2,707.9,663.1,2789.2,1591.2,855.7,700.1,3147.0,11.90%,20.55%,5.28%,12.52%
88,of which: OECD,830.8,378.8,389.8,1599.3,932.9,455.7,400.0,1788.6,11.98%,19.99%,2.34%,11.53%
89,Non-OECD,587.3,329.2,273.4,1189.9,658.3,400.0,300.1,1358.4,11.77%,21.19%,9.47%,13.85%
90,European Union,364.5,125.2,168.8,658.5,394.7,146.1,169.6,710.4,7.98%,16.36%,0.19%,7.58%
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Source: statistics are taken from national sta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,Based on gross generation and not accounting f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,* Includes electricity generated from: geother...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,^ Less than 0.05.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,♦ Less than 0.05%.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,A more extensive time series of renewables by ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Note: Growth rates are adjusted for leap years.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
renew_gen_by_source = renew_gen_by_source.drop(index=[86,87,88,89,90,91,92,93,94,95,96,97,98])
renew_gen_by_source.tail(8)

,Terawatt-hours,2019 Wind,2019 Solar,Other renewables*,2019 Total,2020 Wind,2020 Solar,Other renewables*.1,2020 Total,2020 Growth Rate Wind,2020 Growth Rate Solar,Other renewables*.2,2020 Growth Rate Total
78,Singapore,-,0.2,0.8,1.0,-,0.3,0.7,1.0,0.00%,51.22%,-10.88%,1.77%
79,South Korea,2.7,13.0,14.9,30.5,3.1,16.6,17.3,37.0,16.87%,27.14%,16.44%,21.03%
80,Sri Lanka,0.3,0.4,0.1,0.8,0.6,0.4,0.1,1.1,95.61%,6.88%,-0.27%,42.58%
81,Taiwan,1.9,4.0,2.0,7.9,2.3,6.1,1.9,10.3,20.65%,51.19%,-2.23%,30.45%
82,Thailand,2.2,4.6,14.6,21.4,2.2,4.6,13.7,20.5,-0.27%,-0.27%,-6.43%,-4.47%
83,Vietnam,^,4.1,^,4.1,^,9.5,^,9.5,60.74%,128.96%,-7.03%,128.94%
84,Other Asia Pacific,0.5,0.8,0.3,1.5,0.5,1.1,0.2,1.7,-0.28%,27.37%,-10.88%,12.84%
85,Total Asia Pacific,509.4,392.0,247.8,1149.2,572.6,470.3,279.1,1322.0,12.11%,19.63%,12.31%,14.72%